site_name: NAS uCore setup
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.footnote.tooltips

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
